/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaventasweb.gui;

import com.mycompany.sistemaventasweb.clases.Post;
import java.awt.Color;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author melb
 */
public class GUIForo extends javax.swing.JFrame {

    /**
     * Creates new form GUIForo
     */
    
    int xMouse, yMouse;
    GUIPost iPost = new GUIPost();
    GUIPage iPage = new GUIPage();
    DefaultTableModel modelo;
    private int selectedRow = -1;
    
    public GUIForo() {
        
        initComponents();
        iPost.cargarDatos();
        
        //Setear titulos de tabla
        String [] titulos = {"Titulo","Autor","Disco","Contenido"};
        modelo = new DefaultTableModel(null,titulos);
        tblPosts.setModel(modelo);
        
        cargarPostsEnTabla();
        
        defaultCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnAddPost = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblRightBg = new javax.swing.JLabel();
        lblTituloForo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JPanel();
        lblTxtCerrarSesion = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblNuevoPost = new javax.swing.JLabel();
        txtDiscoPost = new javax.swing.JTextField();
        txtAutorPost = new javax.swing.JTextField();
        txtTituloPost = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        lblTituloPost = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPost = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPosts = new javax.swing.JTable();
        lblListaPosts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon("/home/melb/NetBeansProjects/sistemaVentasWeb/src/main/java/com/mycompany/sistemaventasweb/resources/disco3.png")); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        btnAddPost.setBackground(new java.awt.Color(255, 102, 153));
        btnAddPost.setFont(new java.awt.Font("Roboto Slab", 1, 13)); // NOI18N
        btnAddPost.setForeground(new java.awt.Color(0, 0, 0));
        btnAddPost.setIcon(new javax.swing.ImageIcon("/home/melb/NetBeansProjects/sistemaVentasWeb/src/main/java/com/mycompany/sistemaventasweb/resources/iconos/mas.png")); // NOI18N
        btnAddPost.setText("Post");
        btnAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPostActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 110, -1));

        btnCancelar.setBackground(new java.awt.Color(255, 102, 153));
        btnCancelar.setFont(new java.awt.Font("Roboto Slab", 1, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setIcon(new javax.swing.ImageIcon("/home/melb/NetBeansProjects/sistemaVentasWeb/src/main/java/com/mycompany/sistemaventasweb/resources/iconos/cruz.png")); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 110, -1));

        lblRightBg.setIcon(new javax.swing.ImageIcon("/home/melb/NetBeansProjects/sistemaVentasWeb/src/main/java/com/mycompany/sistemaventasweb/resources/bgImagen.jpg")); // NOI18N
        lblRightBg.setText("jLabel1");
        jPanel1.add(lblRightBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 140, 500));

        lblTituloForo.setFont(new java.awt.Font("Roboto Slab", 1, 24)); // NOI18N
        lblTituloForo.setForeground(new java.awt.Color(255, 102, 153));
        lblTituloForo.setText("FORO DE DISCUSION");
        jPanel1.add(lblTituloForo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        exitTxt.setForeground(new java.awt.Color(255, 102, 153));
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCerrarSesionMouseExited(evt);
            }
        });

        lblTxtCerrarSesion.setFont(new java.awt.Font("Roboto Slab", 1, 10)); // NOI18N
        lblTxtCerrarSesion.setForeground(new java.awt.Color(255, 102, 153));
        lblTxtCerrarSesion.setText("LogOut");

        lblCerrarSesion.setIcon(new javax.swing.ImageIcon("/home/melb/NetBeansProjects/sistemaVentasWeb/src/main/java/com/mycompany/sistemaventasweb/resources/iconos/salida.png")); // NOI18N

        javax.swing.GroupLayout btnCerrarSesionLayout = new javax.swing.GroupLayout(btnCerrarSesion);
        btnCerrarSesion.setLayout(btnCerrarSesionLayout);
        btnCerrarSesionLayout.setHorizontalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTxtCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnCerrarSesionLayout.setVerticalGroup(
            btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnCerrarSesionLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblTxtCerrarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        lblHome.setIcon(new javax.swing.ImageIcon("/home/melb/NetBeansProjects/sistemaVentasWeb/src/main/java/com/mycompany/sistemaventasweb/resources/iconos/hogar.png")); // NOI18N

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
            .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnHomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblHome)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnHomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblHome)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 500, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        lblUser.setFont(new java.awt.Font("Roboto Black", 1, 13)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 102, 153));
        lblUser.setIcon(new javax.swing.ImageIcon("/home/melb/NetBeansProjects/sistemaVentasWeb/src/main/java/com/mycompany/sistemaventasweb/resources/iconos/usuario.png")); // NOI18N
        lblUser.setText("Bienvenido!");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        lblNuevoPost.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        lblNuevoPost.setForeground(new java.awt.Color(255, 102, 153));
        lblNuevoPost.setText("Post reciente:");
        jPanel1.add(lblNuevoPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        txtDiscoPost.setBackground(new java.awt.Color(255, 255, 255));
        txtDiscoPost.setFont(new java.awt.Font("Roboto Slab", 1, 13)); // NOI18N
        txtDiscoPost.setForeground(new java.awt.Color(204, 204, 204));
        txtDiscoPost.setText("Nombre del disco");
        txtDiscoPost.setBorder(null);
        jPanel1.add(txtDiscoPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 180, -1));

        txtAutorPost.setBackground(new java.awt.Color(255, 255, 255));
        txtAutorPost.setFont(new java.awt.Font("Roboto Slab", 1, 13)); // NOI18N
        txtAutorPost.setForeground(new java.awt.Color(204, 204, 204));
        txtAutorPost.setText("Autor del post");
        txtAutorPost.setBorder(null);
        jPanel1.add(txtAutorPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));

        txtTituloPost.setBackground(new java.awt.Color(255, 255, 255));
        txtTituloPost.setFont(new java.awt.Font("Roboto Slab", 1, 13)); // NOI18N
        txtTituloPost.setForeground(new java.awt.Color(204, 204, 204));
        txtTituloPost.setText("Titulo del post");
        txtTituloPost.setBorder(null);
        jPanel1.add(txtTituloPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 180, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 180, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 180, 20));

        lblTituloPost.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        lblTituloPost.setForeground(new java.awt.Color(255, 102, 153));
        lblTituloPost.setText("Contenido del post:");
        jPanel1.add(lblTituloPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        txtAreaPost.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaPost.setColumns(20);
        txtAreaPost.setForeground(new java.awt.Color(255, 102, 153));
        txtAreaPost.setRows(5);
        txtAreaPost.setBorder(null);
        jScrollPane1.setViewportView(txtAreaPost);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 360, 110));

        tblPosts.setBackground(new java.awt.Color(255, 255, 255));
        tblPosts.setFont(new java.awt.Font("Roboto Slab", 1, 14)); // NOI18N
        tblPosts.setForeground(new java.awt.Color(255, 102, 153));
        tblPosts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPosts.setToolTipText("");
        tblPosts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPostsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPosts);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 610, 200));

        lblListaPosts.setFont(new java.awt.Font("Roboto Slab", 1, 18)); // NOI18N
        lblListaPosts.setForeground(new java.awt.Color(255, 102, 153));
        lblListaPosts.setText("LISTA DE POSTS");
        jPanel1.add(lblListaPosts, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Metodo limpiar campos
    
    public void limpiarCampos(){
        
        txtTituloPost.setText("");
        txtAreaPost.setText("");
        txtAutorPost.setText("");
        txtDiscoPost.setText("");
        
    }
    
    public void defaultCampos(){
        
        btnAddPost.setEnabled(true);
        btnCancelar.setEnabled(false);
        txtTituloPost.setEditable(false);
        txtAutorPost.setEditable(false);
        txtDiscoPost.setEditable(false);
        txtAreaPost.setEditable(false);
        
    }
    
        private void cargarPostsEnTabla() {
        List<Post> posts = iPost.getPosts();
        for (Post post : posts) {
            String[] rowData = {
                post.getTitulo(),
                post.getAutor(),
                post.getDiscoPost(),
                post.getContenido()
            };
            modelo.addRow(rowData);
        }
    }
        
    public void definirUsuarioComun(){
        
        lblUser.setText("¡Bienvenido User!");
        
    }    
       
    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
         System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        btnExit.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        btnExit.setBackground(Color.white);
        exitTxt.setForeground(new Color(255, 102, 153));
    }//GEN-LAST:event_exitTxtMouseExited

    private void btnCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseClicked
        this.setVisible(false);
        GUILogIn iLogIn = new GUILogIn();
        iLogIn.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionMouseClicked

    private void btnCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseEntered
        btnCerrarSesion.setBackground(Color.red);
        lblTxtCerrarSesion.setForeground(Color.white);
    }//GEN-LAST:event_btnCerrarSesionMouseEntered

    private void btnCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarSesionMouseExited
        btnCerrarSesion.setBackground(Color.white);
        lblTxtCerrarSesion.setForeground(new Color(255, 102, 153));
    }//GEN-LAST:event_btnCerrarSesionMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btnAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPostActionPerformed
        
        this.setVisible(false);
        iPost.setVisible(true);
        iPost.cargarDatos();
        iPost.definirUsuarioComun();
        
    }//GEN-LAST:event_btnAddPostActionPerformed

    private void tblPostsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPostsMouseClicked

        if(evt.getClickCount() == 1){

            JTable receptor = (JTable)evt.getSource();
            selectedRow = receptor.getSelectedRow();

            txtTituloPost.setText(receptor.getModel().getValueAt(selectedRow, 0).toString());
            txtTituloPost.setForeground(Color.black);
            txtAutorPost.setText(receptor.getModel().getValueAt(selectedRow, 1).toString());
            txtAutorPost.setForeground(Color.black);
            txtDiscoPost.setText(receptor.getModel().getValueAt(selectedRow, 2).toString());
            txtDiscoPost.setForeground(Color.black);
            txtAreaPost.setText(receptor.getModel().getValueAt(selectedRow, 3).toString());
            txtDiscoPost.setForeground(Color.black);

            btnAddPost.setEnabled(false);
            btnCancelar.setEnabled(true);

        }

    }//GEN-LAST:event_tblPostsMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        limpiarCampos();
        defaultCampos();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        btnHome.setBackground(Color.red);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        btnHome.setBackground(Color.white);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        this.setVisible(false);
        iPage.setVisible(true);
        if(lblUser.getText().equals("¡Bienvenido User!")){
            iPage.definirUsuarioComun();
            iPage.mostrarBotonesUser();
            iPage.cargarDatos();
        }
    }//GEN-LAST:event_btnHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIForo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIForo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIForo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIForo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIForo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPost;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel btnCerrarSesion;
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnHome;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblListaPosts;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNuevoPost;
    private javax.swing.JLabel lblRightBg;
    private javax.swing.JLabel lblTituloForo;
    private javax.swing.JLabel lblTituloPost;
    private javax.swing.JLabel lblTxtCerrarSesion;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTable tblPosts;
    private javax.swing.JTextArea txtAreaPost;
    private javax.swing.JTextField txtAutorPost;
    private javax.swing.JTextField txtDiscoPost;
    private javax.swing.JTextField txtTituloPost;
    // End of variables declaration//GEN-END:variables
}
